-- =====================================================
-- TOPCON DATABASE EXPORT
-- =====================================================
-- Database: prova_topcon
-- Host: 127.0.0.1:5432
-- Username: topcon
-- Generated: 2026-01-13
-- =====================================================

-- Conectar ao banco de dados
-- psql -h 127.0.0.1 -p 5432 -U topcon -d prova_topcon

-- =====================================================
-- 1. CRIAÇÃO DO BANCO DE DADOS
-- =====================================================

-- Criar banco de dados (executar como superuser)
-- CREATE DATABASE prova_topcon OWNER topcon;

-- =====================================================
-- 2. ESTRUTURA DAS TABELAS
-- =====================================================

-- Tabela: __EFMigrationsHistory (Entity Framework)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Tabela: Usuarios
CREATE TABLE IF NOT EXISTS "Usuarios" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "NomeUsuario" character varying(100),
    "Email" text NOT NULL,
    "SenhaHash" text NOT NULL,
    "Role" character varying(20) NOT NULL DEFAULT 'user',
    "DataCadastro" timestamp with time zone NOT NULL,
    "DataAtualizacao" timestamp with time zone,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

-- Tabela: Postagens
CREATE TABLE IF NOT EXISTS "Postagens" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(200) NOT NULL,
    "Conteudo" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataAtualizacao" timestamp with time zone,
    "UsuarioId" integer NOT NULL,
    CONSTRAINT "PK_Postagens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Postagens_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

-- =====================================================
-- 3. ÍNDICES
-- =====================================================

-- Índice para relacionamento Postagens -> Usuarios
CREATE INDEX IF NOT EXISTS "IX_Postagens_UsuarioId" ON "Postagens" ("UsuarioId");

-- =====================================================
-- 4. DADOS DE EXEMPLO
-- =====================================================

-- Limpar dados existentes (opcional)
-- TRUNCATE TABLE "Postagens" CASCADE;
-- TRUNCATE TABLE "Usuarios" RESTART IDENTITY CASCADE;

-- Inserir histórico de migrações do Entity Framework
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES
('20260112013703_InitialCreate', '6.0.7'),
('20260113012416_AddRoleToUsuario', '6.0.7')
ON CONFLICT ("MigrationId") DO NOTHING;

-- Inserir usuários de teste
INSERT INTO "Usuarios" ("Id", "NomeUsuario", "Email", "SenhaHash", "Role", "DataCadastro", "DataAtualizacao") VALUES
(5, 'Admin', 'admin@gmail.com', '123456', 'admin', '2026-01-12 01:37:03.394000+00', '2026-01-13 01:54:39.167093+00'),
(14, 'Admin Test', 'admin@test.com', '123456', 'admin', '2026-01-13 01:26:08.837120+00', NULL),
(15, 'User Test', 'user@test.com', '123456', 'user', '2026-01-13 01:26:16.374673+00', NULL)
ON CONFLICT ("Id") DO UPDATE SET
    "NomeUsuario" = EXCLUDED."NomeUsuario",
    "Email" = EXCLUDED."Email",
    "SenhaHash" = EXCLUDED."SenhaHash",
    "Role" = EXCLUDED."Role",
    "DataCadastro" = EXCLUDED."DataCadastro",
    "DataAtualizacao" = EXCLUDED."DataAtualizacao";

-- Inserir postagens de exemplo
INSERT INTO "Postagens" ("Id", "Titulo", "Conteudo", "DataCriacao", "DataAtualizacao", "UsuarioId") VALUES
(12, 'novo registro', 'novo registro', '2026-01-13 00:59:16.794000+00', NULL, 5),
(13, 'Bem-vindos ao TopCon!', 'Este é o sistema de postagens TopCon. Aqui você pode compartilhar suas ideias e interagir com outros usuários. Administradores podem criar, editar e deletar postagens, enquanto usuários comuns podem visualizar o conteúdo.', '2026-01-13 02:00:00.000000+00', NULL, 5),
(14, 'Funcionalidades do Sistema', 'O TopCon oferece: Sistema de login com roles, Interface diferenciada por tipo de usuário, Controle de acesso baseado em permissões, Design responsivo e moderno. Desenvolvido com Clean Architecture!', '2026-01-13 02:01:00.000000+00', NULL, 14)
ON CONFLICT ("Id") DO UPDATE SET
    "Titulo" = EXCLUDED."Titulo",
    "Conteudo" = EXCLUDED."Conteudo",
    "DataCriacao" = EXCLUDED."DataCriacao",
    "DataAtualizacao" = EXCLUDED."DataAtualizacao",
    "UsuarioId" = EXCLUDED."UsuarioId";

-- Atualizar sequências para próximos IDs
SELECT setval(pg_get_serial_sequence('"Usuarios"', 'Id'), COALESCE(MAX("Id"), 1)) FROM "Usuarios";
SELECT setval(pg_get_serial_sequence('"Postagens"', 'Id'), COALESCE(MAX("Id"), 1)) FROM "Postagens";


-- =====================================================
-- FIM DO SCRIPT
-- =====================================================